#!/bin/bash

N=1000000000
THREADS=4
if  [[ $# > 0 ]] 
then
	THREADS=$1
fi
echo "Threads set is $1"
echo "Numsteps is $N"
echo ""
echo ""
echo "###############################################################"
echo "###############################################################"
echo "Running exec for pi_1"
./exec1 $THREADS $N
echo ""
echo ""
echo "###############################################################"
echo "###############################################################"
echo "Running exec for pi_2"
./exec2 $THREADS $N
echo ""
echo ""
echo "###############################################################"
echo "###############################################################"
echo "Running exec for pi_3"
./exec3 $THREADS $N
echo ""
